### ISSUE TITLE
#trades occasionally fails with "EOFError: end of file reached "

### ISSUE THREAD

**Issue by YenTheFirst** [sferik/mtgox#1]
EOFError: end of file reached
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/openssl/buffering.rb:145:in `sysread_nonblock'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/openssl/buffering.rb:145:in`read_nonblock'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/protocol.rb:135:in `rbuf_fill'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/protocol.rb:86:in`read'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:2448:in `ensure in read_chunked'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:2448:in`read_chunked'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:2419:in `read_body_0'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:2379:in`read_body'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:905:in `block in get'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1194:in`block in transport_request'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:2342:in `reading_body'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1193:in`transport_request'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1177:in `request'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1170:in`block in request'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:627:in `start'
        from ~/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/net/http.rb:1168:in`request'
... 1 levels...
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/adapter/net_http.rb:49:in `call'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/response.rb:8:in`call'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/response.rb:8:in `call'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/response.rb:8:in`call'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/request/url_encoded.rb:14:in `call'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/request.rb:88:in`run'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/request.rb:28:in `run'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/connection.rb:170:in`run_request'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/faraday-0.6.1/lib/faraday/connection.rb:64:in `get'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/mtgox-0.0.1/lib/mtgox/request.rb:10:in`request'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/mtgox-0.0.1/lib/mtgox/request.rb:4:in `get'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/mtgox-0.0.1/lib/mtgox/client.rb:42:in`trades'
        from ~/.rvm/gems/ruby-1.9.2-p180@global/gems/mtgox-0.0.1/lib/mtgox.rb:14:in `method_missing'
        from bc.rb:157:in`trade_graphs'
        from (irb):571
        from ~/.rvm/rubies/ruby-1.9.2-p180/bin/irb:16:in `<main>'

**Comment by sferik** [comment]
Looks like a `Net::HTTP` error handling a chunked response. I'll write code to make the adapter configurable so you can try using one of the other adapters supported by Faraday.
