### ISSUE TITLE
README documentation on security of transport.

### ISSUE THREAD

**Issue by AgoristRadio** [sferik/mtgox#16]
Could you please document if all API keys and transactions are taking place over SSL/TLS connection or if they are in plaintext.

Thanks.

**Comment by sferik** [comment]
Everything goes over HTTPS, as can be plainly seen in https://github.com/sferik/mtgox/blob/7caa86ca7cf63c72f083e0285c548e9371555b33/lib/mtgox/connection.rb#L19

If you'd like to submit a patch to the README highlighting this fact, I'd be happy to pull it in.
