### ISSUE TITLE
SSLv3 certificate verify fail

### ISSUE THREAD

**Issue by casper** [sferik/mtgox#21]
Hi. On Ubuntu with Ruby 1.9.3 just running the simple example

```
ruby -r rubygems -r mtgox -e "puts MtGox.ticker.sell"
```

I get this:

```
/opt/ruby19/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect 
  returned=1 errno=0 state=SSLv3 read server certificate B: 
  certificate verify failed (Faraday::Error::ConnectionFailed)
```

Any idea how to fix this, or any further information I could provide to help troubleshoot it?

**Comment by casper** [comment]
Figured it out. If anyone else has this problem this fixed it for me:

```
cd /usr/lib/ssl
sudo curl -O http://curl.haxx.se/ca/cacert.pem
sudo mv cacert.pem cert.pem
```

**Comment by yrral86** [comment]
MtGox's cert expired today (April 12th, 2013), so if you see this before they get that fixed, that is likely the cause.
