### ISSUE TITLE
can't used, need to update to new apis

### ISSUE THREAD

**Issue by caoer** [sferik/mtgox#23]
got this warning, many functions are are useable anymore.
THIS API IS DEPRECATED. Please upgrade to newer API such as https://data.mtgox.com/api/2/BTCUSD/money/ticker

**Comment by sferik** [comment]
There is a pull request to do this (#24) but I haven’t merged it yet because I believe it is incomplete. You may want to watch that thread.

**Comment by caoer** [comment]
yes. after changing the url to data.mtgox.com. MtGox.asks can return data, but most of other apis are still no luck. I think upgrade to version 2 will take quite a bit of work.

**Comment by kristianfreeman** [comment]
PR #29 fixed some of this by migrating to the v1 API. @sferik will likely close this soon.
