### ISSUE TITLE
Supporting multiple clients in a given process

### ISSUE THREAD

**Issue by knewter** [sferik/mtgox#37]
So at present, `MtGox` is essentially a singleton.  I have a need to support multiple different logged in gox users in a single process.  I plan to modify this gem to support it, but I wanted to open up a discussion to see if that would be the sort of thing you would care to have submitted.  Otherwise I'll just fork, but I hate to diverge.

It seems that the gem could maintain its current API if `MtGox.new` just memoized a new instance of `MtGox::Client`, and everything else on MtGox proxied through to a new instance.

Does this sound like the sort of PR you'd be interested in?
## Moderately substantial changes resulting from this

So far, I see the following moderately substantial changes that would result from this:
- A Request would have to be scoped to a given client (to get its secret and key)
- We would include `MtGox::Configuration` in `MtGox::Client` 

...aaaaand I think that's it.  `MtGox.key` and `MtGox.secret` aren't used anywhere else.

**Comment by sferik** [comment]
This proposal sounds good to me. If you're looking for inspiration, I'd suggest checking out the [`twitter`](https://github.com/sferik/twitter) library, where I've done essentially what you've described above. Specifically, take a look at [`lib/twitter.rb`](https://github.com/sferik/twitter/blob/master/lib/twitter.rb) and [`lib/twitter/configurable.rb`](https://github.com/sferik/twitter/blob/master/lib/twitter/configurable.rb).
