### ISSUE TITLE
Don't bubble up Exceptions from dependencies?

### ISSUE THREAD

**Issue by knewter** [sferik/mtgox#43]
@sferik, wanted to get your feedback on this.

https://github.com/sferik/mtgox/blob/master/lib/mtgox/client.rb#L270

That bubbles up a Faraday error.  My plan was to define a custom CancelOrderFailedError rather than bubbling up the Faraday error.  That way dependencies up the chain don't have to know implementation details.

Thoughts?  Didn't want to do it if you don't want it :)

**Comment by sferik** [comment]
Yeah, `MtGox` code should not raise a `Faraday` error, it should rescue that and raise a `MtGox` error. Do it.
