### ISSUE TITLE
README examples not working as supposed to

### ISSUE THREAD

**Issue by renich** [sferik/mtgox#46]
Hey guys,

Title is self explanatory. My guess is that it has something to do with: https://github.com/sferik/mtgox/commit/503d88e083bbb025c97a872cad2e6bef317b1933

Anyway, the problem is that I get some weird output after MtGox.balance. It does give me the balance, but like this: 

```
> MtGox.balance
=> [#<MtGox::Balance:0x000000021b2e50
  @amount=#<BigDecimal:21b2ba8,'0.1356836241 2E3',18(27)>,
  @currency="BTC">,
 #<MtGox::Balance:0x000000021b23d8
  @amount=#<BigDecimal:21b2270,'0.44609E0',9(18)>,
  @currency="USD">]
```

and MtGox.balance[0].to_f doesn't work... should it?

**Comment by DarthStrom** [comment]
You should be able to do

```
> MtGox.balance[0].amount.to_f
```

**Comment by knewter** [comment]
@sferik this issue ought to be closed.  Just trying to help triage...

**Comment by sferik** [comment]
@knewter Thanks.
