### ISSUE TITLE
Client does not return trading data

### ISSUE THREAD

**Issue by jottr** [sferik/mtgox#55]
When trying to obtain current ticker data from MtGox, the client always returns the same decimal number. 

In the terminal:

``` btc
0.576E3
```

In irb: 

``` ruby
puts MtGox.ticker.sell
=> #<BigDecimal:239ed40,'0.574995E3',18(36)>
```

Same problem arises when using any of the the other methods, e.g. `MtGox.ticker.asks`

`ruby --version` returns `ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-linux]`

**Comment by sferik** [comment]
If you want a floating point representation of a `BigDecimal`, just call `#to_f` on it.
