### ISSUE TITLE
MtGox's API method 'getTrades' supports parameter 'since'

### ISSUE THREAD

**Issue by xHire** [sferik/mtgox#7]
MtGox's API method 'getTrades' supports parameter 'since' and so should this library. Following code works fine for me (file `lib/mtgox/client.rb`):

``` ruby
def trades since = nil
  get('/code/data/getTrades.php', since ? { :since => since } : {}).sort_by{|trade| trade['date']}.map do |trade|
    Trade.new(trade)
  end
end
```

**Comment by gutenye** [comment]
+1

need this feature.

**Comment by sosiouxme** [comment]
https://github.com/sferik/mtgox/pull/35
