### ISSUE TITLE
undefined method `last' for MtGox::Ticker

### ISSUE THREAD

**Issue by bitcoiners** [sferik/mtgox#8]
I added btc alias to my .bashrc
but when I run btc I get this error:
-e:1:in `<main>': undefined method`last' for #MtGox::Ticker:0x8f8057c (NoMethodError)
using latest gem

**Comment by rmcfadzean** [comment]
The method "last" has been gone for awhile from what I remember.
You probably want the line (in your .bashrc) to read:

```
alias btc='ruby -r rubygems -r mtgox -e "puts MtGox.ticker.sell"'
```

**Comment by bitcoiners** [comment]
Thanks. That worked. You may want to update readme.
